const TRANSLATIONS = {
    sl: {
        appTitle: "Triatlon rezultati",
        language: "Jezik",
        heroTitle: "Spletni pregled triatlonskih rezultatov",
        heroText: "Pregledujte tekmovanja, rezultate, nastope tekmovalcev in primerjajte dosežke.",
        competitions: "Tekmovanja",
        competitors: "Tekmovalci",
        comparison: "Primerjava",
        refresh: "Osveži",
        results: "Rezultati",
        name: "Naziv",
        year: "Leto",
        type: "Tip",
        location: "Lokacija",
        competitor: "Tekmovalec",
        division: "Divizija",
        swim: "Plavanje",
        bike: "Kolesarjenje",
        run: "Tek",
        totalTime: "Skupni čas",
        divisionFilter: "Filter po diviziji",
        clear: "Počisti",
        searchCompetitor: "Iskanje tekmovalca",
        enterCompetitorName: "Vnesi ime tekmovalca",
        search: "Išči",
        fullName: "Ime in priimek",
        age: "Starost",
        country: "Država",
        actions: "Akcije",
        performances: "Nastopi",
        bestTime: "Najboljši čas",
        numberOfPerformances: "Število nastopov",
        selectedCompetitor: "Izbran tekmovalec",
        competitionId: "Tekmovanje ID",
        comparisonHelp: "Tekmovalca izberi v zavihku Tekmovalci z gumboma Izberi 1 in Izberi 2.",
        competitorOne: "Tekmovalec 1",
        competitorTwo: "Tekmovalec 2",
        compare: "Primerjaj",
        statistic: "Statistika",
        footerText: "OZRA Naloga 4 - spletna aplikacija",
        selectCompetition: "Izberi tekmovanje za prikaz rezultatov.",
        noData: "Ni podatkov za prikaz.",
        loading: "Nalaganje podatkov ...",
        serverError: "Napaka pri povezavi s strežnikom. Preveri, ali je Flask API zagnan.",
        enterNameWarning: "Vnesi ime tekmovalca.",
        selectFirst: "Izberi 1",
        selectSecond: "Izberi 2",
        showPerformances: "Nastopi",
        selected: "Izbrano",
        displayedLimited: "Prikazanih je največ",
        of: "od",
        rows: "vrstic"
    },

    en: {
        appTitle: "Triathlon Results",
        language: "Language",
        heroTitle: "Web overview of triathlon results",
        heroText: "Browse competitions, results, competitor performances and compare achievements.",
        competitions: "Competitions",
        competitors: "Competitors",
        comparison: "Comparison",
        refresh: "Refresh",
        results: "Results",
        name: "Name",
        year: "Year",
        type: "Type",
        location: "Location",
        competitor: "Competitor",
        division: "Division",
        swim: "Swim",
        bike: "Bike",
        run: "Run",
        totalTime: "Total time",
        divisionFilter: "Filter by division",
        clear: "Clear",
        searchCompetitor: "Search competitor",
        enterCompetitorName: "Enter competitor name",
        search: "Search",
        fullName: "Full name",
        age: "Age",
        country: "Country",
        actions: "Actions",
        performances: "Performances",
        bestTime: "Best time",
        numberOfPerformances: "Number of performances",
        selectedCompetitor: "Selected competitor",
        competitionId: "Competition ID",
        comparisonHelp: "Select competitors in the Competitors tab using Select 1 and Select 2 buttons.",
        competitorOne: "Competitor 1",
        competitorTwo: "Competitor 2",
        compare: "Compare",
        statistic: "Statistic",
        footerText: "OZRA Assignment 4 - web application",
        selectCompetition: "Select a competition to display results.",
        noData: "No data to display.",
        loading: "Loading data ...",
        serverError: "Server connection error. Check if the Flask API is running.",
        enterNameWarning: "Enter competitor name.",
        selectFirst: "Select 1",
        selectSecond: "Select 2",
        showPerformances: "Performances",
        selected: "Selected",
        displayedLimited: "Displaying maximum",
        of: "of",
        rows: "rows"
    }
};

function tr(key) {
    const lang = AppState.lang || "sl";
    return TRANSLATIONS[lang][key] || key;
}